package com.bert.jetcache.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.annotation.Generated;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TUser implements Serializable {

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: t_user.id")
    private Long id;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: t_user.name")
    private String name;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: t_user.age")
    private Integer age;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: t_user.money")
    private BigDecimal money;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: t_user.create_at")
    private Date createAt;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: t_user.update_at")
    private Date updateAt;
}